'use client'

import { useEffect, useState } from 'react'
import { getField, mediaTitle, mediaType } from '../../lib/nuvio'
import { Icon } from '../ui/Icon'
import { ManagementToolbar } from '../ui/ManagementToolbar'

export function WatchPage({rows,history,addons,loading,error,hasMore,onLoadMore}:any){
  const [q,setQ]=useState(''); const [filter,setFilter]=useState('unfinished'); const [group,setGroup]=useState(true); const [selected,setSelected]=useState<any|null>(null); const [resolving,setResolving]=useState(false)
  const [records,setRecords]=useState<any[]>(()=>normalizeWatch(rows,history))
  useEffect(()=>{setRecords(normalizeWatch(rows,history))},[rows,history])
  async function resolveTitles(){
    const missing=records.filter(x=>!x.title||x.title==='Sem título').slice(0,60); if(!missing.length)return
    setResolving(true)
    try{const r=await fetch('/api/nuvio/resolve-watch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({addons,items:missing.map(x=>({key:x.key,contentId:x.contentId,type:x.type}))})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao buscar metadados');if(Array.isArray(d.resolved)&&d.resolved.length){const by=new Map<string,any>(d.resolved.map((x:any)=>[String(x.key),x] as [string,any]));setRecords(prev=>prev.map(x=>{const hit=by.get(x.key);return hit?{...x,...hit,title:hit.title||x.title}:x}))}else alert('Nenhum título adicional foi encontrado nos addons de metadados.') }catch(e:any){alert(e.message||'Falha ao resolver títulos')}finally{setResolving(false)}
  }
  const filtered=records.filter((x:any)=>{const title=String(x.title||'Sem título').toLowerCase();const match=title.includes(q.toLowerCase())||x.key.toLowerCase().includes(q.toLowerCase());const state=filter==='all'||(filter==='unfinished'&&!x.finished)||(filter==='finished'&&x.finished);return match&&state})
  const groups:any[][]=group?Object.values(filtered.reduce((m:any,x:any)=>{const k=x.seriesKey||x.key;(m[k]??=[]).push(x);return m},{})) as any[][]:filtered.map((x:any)=>[x])
  return <div className="stack management-page personal-data-page"><ManagementToolbar value={q} onChange={setQ} label="Filtrar títulos de progresso" placeholder="Buscar título ou identificador…"><span className="management-count">{records.length} itens</span><select aria-label="Filtrar progresso por estado" className="toolbar-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="unfinished">Em andamento</option><option value="finished">Já assistidos</option><option value="all">Todos</option></select><button type="button" className={group?'primary':'ghost'} aria-pressed={group} onClick={()=>setGroup(!group)}>{group?'Agrupado':'Separado'}</button><button type="button" className="ghost" disabled={resolving} onClick={resolveTitles}><Icon name="refresh" size={17}/>{resolving?'Buscando títulos…':'Corrigir títulos'}</button></ManagementToolbar>
    <div className="watch-summary"><span>{records.filter((x:any)=>!x.finished).length} em andamento</span><span>{records.filter((x:any)=>x.finished).length} assistidos</span><span>{new Set(records.map((x:any)=>x.seriesKey||x.key)).size} grupos</span></div>
    {error&&<div className="notice error" role="alert">{error}</div>}{loading&&<div className="notice" role="status">Carregando histórico…</div>}{(hasMore||error)&&<button className="ghost" disabled={loading} onClick={onLoadMore}>{loading?'Carregando…':error?'Tentar carregar histórico novamente':'Carregar mais histórico'}</button>}
    <div className="watch-groups">{groups.map((g:any[],i:number)=><div className="panel watch-group" key={i}><div className="watch-group-head"><div><h3>{g[0].seriesTitle||g[0].title||'Sem título'}</h3><span>{g.length>1?`${g.length} episódios`:g[0].type==='series'?'Série':'Filme'}</span></div><span className="number-chip">{g.filter(x=>!x.finished).length} pendentes</span></div>{g.map((x:any)=><WatchCard item={x} key={x.key} onOpen={()=>setSelected(x)}/>)}</div>)}{!groups.length&&<div className="panel empty">Nenhum item corresponde ao filtro.</div>}</div>
    {selected&&<ScreenDrawer title={selected.title||'Detalhes do item'} close={()=>setSelected(null)}><div className="detail-cards"><div><span>Estado</span><b>{selected.finished?'Assistido':'Em andamento'}</b></div><div><span>Tipo</span><b>{selected.type||'—'}</b></div><div><span>Temporada</span><b>{selected.season??'—'}</b></div><div><span>Episódio</span><b>{selected.episode??'—'}</b></div><div><span>Progresso</span><b>{selected.pct?`${Math.round(selected.pct)}%`:'—'}</b></div><div><span>Última atividade</span><b>{selected.lastWatched?new Date(Number(selected.lastWatched)).toLocaleString('pt-BR'):'—'}</b></div></div><p className="security-note">O Watch Progress sincronizado registra posição, duração, episódio e identificadores. A fonte/servidor exato do stream não é mantido nesse registro, então o painel não consegue recuperar por qual addon/servidor você assistiu.</p><details><summary>Dados técnicos</summary><pre>{JSON.stringify(selected,null,2)}</pre></details></ScreenDrawer>}
  </div>
}
function normalizeWatch(rows:any[],history:any[]){
  const all=[...rows.map(x=>({...x,__source:'progress'})),...history.map(x=>({...x,__source:'history'}))]
  const historyKeys=new Set<string>(); for(const x of all.filter(x=>x.__source==='history')) historyKeys.add(watchIdentity(x))
  const map=new Map<string,any>()
  for(const x of all){
    const title=mediaTitle(x); const season=getField(x,['season','season_number','seasonNumber'],null); const episode=getField(x,['episode','episode_number','episodeNumber'],null); const contentId=String(getField(x,['content_id','contentId','parentContentId','id','video_id','videoId'],'')).trim(); const key=contentId||`${title}|${season||''}|${episode||''}`; const watched=Number(getField(x,['position','progress','playback_position'],0)||0); const duration=Number(getField(x,['duration','runtime','total','video_duration'],0)||0); const pct=duration>0?Math.min(100,watched/duration*100):Number(getField(x,['percent','progress_percent','progressPercent'],0)||0); const finished=x.__source==='history'||Boolean(x.finished||x.completed||pct>=95||x.watched===true)||historyKeys.has(watchIdentity(x)); const seriesTitle=getField(x,['series_title','seriesName','show_title','parentTitle'],null)||((season!=null||episode!=null)?title:null); const seriesIds=[x?.series_id,x?.seriesId,x?.show_id,x?.showId,x?.parentContentId]; const seriesId=seriesIds.find(v=>v!==undefined&&v!==null&&String(v).trim()); const sk=seriesId?`id:${String(seriesId).toLowerCase()}`:`title:${String(seriesTitle||title).trim().toLowerCase()}`; const old=map.get(key); const candidate={...x,key,title,contentId,seriesKey:sk,seriesTitle,season,episode,pct,finished,type:(season!=null||episode!=null)?'series':mediaType(x),poster:getField(x,['poster','poster_url','posterUrl'],null)||x?.meta?.poster,lastWatched:getField(x,['lastWatched','last_watched','updated_at','updatedAt'],null),position:watched,duration}
    if(!old||Number(candidate.pct)>Number(old.pct)||candidate.finished&&!old.finished)map.set(key,candidate)
  }
  return Array.from(map.values()).sort((a,b)=>Number(b.lastWatched||0)-Number(a.lastWatched||0)||Number(b.pct)-Number(a.pct))
}
function watchIdentity(x:any){return String(getField(x,['content_id','contentId','parentContentId','id','video_id','videoId'],mediaTitle(x))).toLowerCase()}
function WatchCard({item,onOpen}:any){return <button className="watch-card watch-card-button" onClick={onOpen}>{item.poster?<img src={item.poster} alt=""/>:<div className="poster-fallback">▶</div>}<div className="watch-body"><b>{item.title||'Sem título'}</b><span>{item.seriesTitle&&item.seriesTitle!==item.title?`${item.seriesTitle} · `:''}{item.season!=null?`T${item.season}`:''}{item.episode!=null?` · E${item.episode}`:''}</span><div className="progress-track"><i style={{width:`${Math.round(item.pct||0)}%`}}></i></div><small>{item.finished?'Assistido':item.pct?`${Math.round(item.pct)}% assistido`:'Progresso não informado'} · Toque para detalhes</small></div></button>}

export function LibraryPage({rows,token,profile,onUpdate,loading,error,hasMore,onLoadMore}:any){
  const [q,setQ]=useState(''),[source,setSource]=useState<'nuvio'|'trakt'>('nuvio'),[trakt,setTrakt]=useState<any[]>([]),[clientId,setClientId]=useState(''),[accessToken,setAccessToken]=useState(''),[busy,setBusy]=useState(false)
  const filtered=rows.filter((x:any)=>mediaTitle(x).toLowerCase().includes(q.toLowerCase()))
  async function loadTrakt(){if(!clientId||!accessToken){alert('Informe Client ID e Access Token do Trakt.');return}setBusy(true);try{const r=await fetch('/api/trakt/collection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,accessToken})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Trakt recusou a consulta.');setTrakt([...(d.movies||[]).map((x:any)=>({...x,media_type:'movie',title:x.movie?.title,poster:x.movie?.images?.poster?.[0]})),...(d.shows||[]).map((x:any)=>({...x,media_type:'show',title:x.show?.title,poster:x.show?.images?.poster?.[0]}))]);setSource('trakt')}catch(e:any){alert(e.message||'Falha no Trakt')}finally{setBusy(false)}}
  async function pushTrakt(){if(!clientId||!accessToken){alert('Informe Client ID e Access Token do Trakt.');return}setBusy(true);try{const r=await fetch('/api/trakt/sync-collection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId,accessToken,items:rows})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao enviar para Trakt');alert('Trakt recebeu '+(d.sent||0)+' item(ns). Itens sem ID reconhecível foram ignorados.')}catch(e:any){alert(e.message||'Falha no Trakt')}finally{setBusy(false)}}
  return <div className="stack management-page personal-data-page"><ManagementToolbar value={q} onChange={setQ} label="Buscar títulos na biblioteca" placeholder="Buscar na biblioteca…"><span className="management-count">{profile.libraryLoaded===false?'…':source==='nuvio'?rows.length:trakt.length} itens</span><button type="button" className={source==='nuvio'?'primary':'ghost'} aria-pressed={source==='nuvio'} onClick={()=>setSource('nuvio')}>Nuvio</button><button type="button" className={source==='trakt'?'primary':'ghost'} aria-pressed={source==='trakt'} onClick={()=>setSource('trakt')}>Trakt</button></ManagementToolbar>
    {error&&<div className="notice error" role="alert">{error}</div>}{loading&&<div className="notice" role="status">Carregando biblioteca…</div>}
    {source==='trakt'&&<section className="trakt-panel"><div className="trakt-heading"><b>Conectar ao Trakt</b><span>Consulta sua collection e permite enviar os itens da biblioteca Nuvio. As credenciais ficam nesta sessão do navegador.</span></div><label><span>Client ID</span><input autoComplete="off" placeholder="Client ID" value={clientId} onChange={e=>setClientId(e.target.value)}/></label><label><span>Access Token</span><input autoComplete="off" placeholder="Access Token" type="password" value={accessToken} onChange={e=>setAccessToken(e.target.value)}/></label><div className="trakt-actions"><button className="ghost" disabled={busy} onClick={loadTrakt}><Icon name="refresh" size={16}/>{busy?'Consultando…':'Consultar Trakt'}</button><button className="primary" disabled={busy||!rows.length} onClick={pushTrakt}>Nuvio → Trakt</button></div></section>}
    {source==='trakt'?<div className="library-grid">{trakt.filter(x=>String(x.title||'').toLowerCase().includes(q.toLowerCase())).map((x:any,i:number)=><div className="library-card" key={i}>{x.poster?<img src={x.poster} alt=""/>:<div className="poster-fallback">TV</div>}<div><b>{x.title}</b><small>Trakt · {x.media_type}</small></div></div>)}</div>:<><div className="library-grid">{filtered.map((x:any,i:number)=><div className="library-card" key={x.id||x.content_id||i}><div className="poster-fallback">LIB</div><div><b>{mediaTitle(x)}</b><small>{mediaType(x)}</small></div></div>)}</div>{(hasMore||error)&&<button className="ghost" disabled={loading} onClick={onLoadMore}>{loading?'Carregando…':error?'Tentar carregar biblioteca novamente':'Carregar mais itens'}</button>}</>}
  </div>
}

function ScreenDrawer({title,close,children}:any){return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer" role="dialog" aria-modal="true" aria-labelledby="profile-data-drawer-title"><div className="drawer-head"><div><div className="eyebrow">DETALHES</div><h2 id="profile-data-drawer-title">{title}</h2></div><button className="icon-btn" onClick={close} aria-label="Fechar detalhes">×</button></div>{children}</aside></div>}
